<?php  $output .= '<ul class="">

				</ul>

				<ul class="nav-child">
					<li class="hn"><strong><a href="http://localhost/bilddatenbank/de/kategorien/">Start Categories</a></strong></li>


				</ul>

				<ul class="nav-child">
					<li class="hn"><strong><a href="http://localhost/bilddatenbank/de/infos/">Infos</a></strong></li>


				</ul>

				<ul class="nav-child">
					<li class="hn"><strong><a href="http://localhost/bilddatenbank/de/profil/">Profile</a></strong></li>


				</ul>

				<ul class="nav-child">
					<li class="hn"><strong><a href="http://localhost/bilddatenbank/de/kategory-group/">Group</a></strong></li>


				</ul>

				<ul class="nav-child">
					<li class="hn"><strong><a href="http://localhost/bilddatenbank/de/tag/">tag</a></strong></li>


				</ul>

				<ul class="nav-child">
					<li class="hn"><strong><a href="http://localhost/bilddatenbank/de/tag-group/">tagGroup</a></strong></li>
					<li class="sn"><a href="http://localhost/bilddatenbank/de/neuigkeiten/dienstanweisungen/">Dienstanweisungen</a></li>
					<li class="sn"><a href="http://localhost/bilddatenbank/de/neuigkeiten/neuigkeiten-vom-stift/">Neuigkeiten vom Stift</a></li>
					<li class="sn"><a href="http://localhost/bilddatenbank/de/neuigkeiten/neuigkeiten-veranstaltungen/">Neuigkeiten Veranstaltungen</a></li>
					<li class="sn"><a href="http://localhost/bilddatenbank/de/neuigkeiten/neuigkeiten-oberrad/">Neuigkeiten Oberrad</a></li>
</ul>'; ?>