<?php  $output .= '<ul class="">

				</ul>

				<ul class="nav-child">
					<li class="hn"><strong><a href="http://php7.pixeldusche.com/bilddatenbank/de/infos/">Infos</a></strong></li>


				</ul>

				<ul class="nav-child">
					<li class="hn"><strong><a href="http://php7.pixeldusche.com/bilddatenbank/de/ordner/">Dateiordner/Schlagworte</a></strong></li>


				</ul>

				<ul class="nav-child">
					<li class="hn"><strong><a href="http://php7.pixeldusche.com/bilddatenbank/de/suchbegriffe/">Verwaltung Suchbegriffe</a></strong></li>


				</ul>

				<ul class="nav-child">
					<li class="hn"><strong><a href="http://php7.pixeldusche.com/bilddatenbank/de/suchbegriffe-gruppe/">Verwaltung Suchbegriffe Gruppen</a></strong></li>
</ul>'; ?>