
<?php  $structure = '<ul class="sitemap"><li class="closeHeader"><i class="fa fa-close"></i></li>
		<li><a href="http://php7.pixeldusche.com/bilddatenbank/de/infos/" title="infos"><strong>Infos</strong></a></li>
			<li><a href="http://php7.pixeldusche.com/bilddatenbank/de/ordner/" title="dateiordner-schlagworte"><strong>Dateiordner/Schlagworte</strong></a></li>
			<li><a href="http://php7.pixeldusche.com/bilddatenbank/de/suchbegriffe/" title="verwaltung-suchbegriffe"><strong>Verwaltung Suchbegriffe</strong></a></li>
			<li><a href="http://php7.pixeldusche.com/bilddatenbank/de/suchbegriffe-gruppe/" title="verwaltung-suchbegriffe-gruppen"><strong>Verwaltung Suchbegriffe Gruppen</strong></a></li>
	</ul>
';
?>
</ul>