
<?php  $structure = '<ul class="sitemap"><li class="closeHeader"><i class="fa fa-close"></i></li>
		<li><a href="http://php7.pixeldusche.com/bilddatenbank/de/infos/" title="infos"><strong>Infos</strong></a></li>
			<li><a href="http://php7.pixeldusche.com/bilddatenbank/de/profil/" title="profile"><strong>Profile</strong></a></li>
			<li><a href="http://php7.pixeldusche.com/bilddatenbank/de/kategory-group/" title="group"><strong>Group</strong></a></li>
			<li><a href="http://php7.pixeldusche.com/bilddatenbank/de/tag/" title="tag"><strong>tag</strong></a></li>
			<li><a href="http://php7.pixeldusche.com/bilddatenbank/de/tag-group/" title="taggroup"><strong>tagGroup</strong></a></li>
	</ul>
';
?>
</ul>